<?php

namespace ContainerTx1r1qv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JzOJ74VService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JzOJ74V' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JzOJ74V'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\BaseController::ajout' => ['privates', '.service_locator.gRXaggr', 'get_ServiceLocator_GRXaggrService', true],
            'App\\Controller\\BaseController::ajoutDeGenre' => ['privates', '.service_locator.cwjrQ4b', 'get_ServiceLocator_CwjrQ4bService', true],
            'App\\Controller\\BaseController::ajoutDeType' => ['privates', '.service_locator.cwjrQ4b', 'get_ServiceLocator_CwjrQ4bService', true],
            'App\\Controller\\BaseController::ajoutPanier' => ['privates', '.service_locator.cwjrQ4b', 'get_ServiceLocator_CwjrQ4bService', true],
            'App\\Controller\\BaseController::contact' => ['privates', '.service_locator.fAuq5JK', 'get_ServiceLocator_FAuq5JKService', true],
            'App\\Controller\\BaseController::detail' => ['privates', '.service_locator.cwjrQ4b', 'get_ServiceLocator_CwjrQ4bService', true],
            'App\\Controller\\BaseController::favorie' => ['privates', '.service_locator.cwjrQ4b', 'get_ServiceLocator_CwjrQ4bService', true],
            'App\\Controller\\BaseController::index' => ['privates', '.service_locator.cwjrQ4b', 'get_ServiceLocator_CwjrQ4bService', true],
            'App\\Controller\\BaseController::monPanier' => ['privates', '.service_locator.cwjrQ4b', 'get_ServiceLocator_CwjrQ4bService', true],
            'App\\Controller\\BaseController::supprimerPanier' => ['privates', '.service_locator.cwjrQ4b', 'get_ServiceLocator_CwjrQ4bService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.e_4zbH4', 'get_ServiceLocator_E4zbH4Service', true],
            'App\\Controller\\RegistrationController::verifyUserEmail' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\SearchController::rechercheLivre' => ['privates', '.service_locator.cwjrQ4b', 'get_ServiceLocator_CwjrQ4bService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\BaseController:ajout' => ['privates', '.service_locator.gRXaggr', 'get_ServiceLocator_GRXaggrService', true],
            'App\\Controller\\BaseController:ajoutDeGenre' => ['privates', '.service_locator.cwjrQ4b', 'get_ServiceLocator_CwjrQ4bService', true],
            'App\\Controller\\BaseController:ajoutDeType' => ['privates', '.service_locator.cwjrQ4b', 'get_ServiceLocator_CwjrQ4bService', true],
            'App\\Controller\\BaseController:ajoutPanier' => ['privates', '.service_locator.cwjrQ4b', 'get_ServiceLocator_CwjrQ4bService', true],
            'App\\Controller\\BaseController:contact' => ['privates', '.service_locator.fAuq5JK', 'get_ServiceLocator_FAuq5JKService', true],
            'App\\Controller\\BaseController:detail' => ['privates', '.service_locator.cwjrQ4b', 'get_ServiceLocator_CwjrQ4bService', true],
            'App\\Controller\\BaseController:favorie' => ['privates', '.service_locator.cwjrQ4b', 'get_ServiceLocator_CwjrQ4bService', true],
            'App\\Controller\\BaseController:index' => ['privates', '.service_locator.cwjrQ4b', 'get_ServiceLocator_CwjrQ4bService', true],
            'App\\Controller\\BaseController:monPanier' => ['privates', '.service_locator.cwjrQ4b', 'get_ServiceLocator_CwjrQ4bService', true],
            'App\\Controller\\BaseController:supprimerPanier' => ['privates', '.service_locator.cwjrQ4b', 'get_ServiceLocator_CwjrQ4bService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.e_4zbH4', 'get_ServiceLocator_E4zbH4Service', true],
            'App\\Controller\\RegistrationController:verifyUserEmail' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\SearchController:rechercheLivre' => ['privates', '.service_locator.cwjrQ4b', 'get_ServiceLocator_CwjrQ4bService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\BaseController::ajout' => '?',
            'App\\Controller\\BaseController::ajoutDeGenre' => '?',
            'App\\Controller\\BaseController::ajoutDeType' => '?',
            'App\\Controller\\BaseController::ajoutPanier' => '?',
            'App\\Controller\\BaseController::contact' => '?',
            'App\\Controller\\BaseController::detail' => '?',
            'App\\Controller\\BaseController::favorie' => '?',
            'App\\Controller\\BaseController::index' => '?',
            'App\\Controller\\BaseController::monPanier' => '?',
            'App\\Controller\\BaseController::supprimerPanier' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RegistrationController::verifyUserEmail' => '?',
            'App\\Controller\\SearchController::rechercheLivre' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\BaseController:ajout' => '?',
            'App\\Controller\\BaseController:ajoutDeGenre' => '?',
            'App\\Controller\\BaseController:ajoutDeType' => '?',
            'App\\Controller\\BaseController:ajoutPanier' => '?',
            'App\\Controller\\BaseController:contact' => '?',
            'App\\Controller\\BaseController:detail' => '?',
            'App\\Controller\\BaseController:favorie' => '?',
            'App\\Controller\\BaseController:index' => '?',
            'App\\Controller\\BaseController:monPanier' => '?',
            'App\\Controller\\BaseController:supprimerPanier' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RegistrationController:verifyUserEmail' => '?',
            'App\\Controller\\SearchController:rechercheLivre' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
