<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\ContainerAwVMSpP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAwVMSpP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAwVMSpP.legacy');
=======
if (\class_exists(\ContainerTx1r1qv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTx1r1qv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTx1r1qv.legacy');
>>>>>>> 82883b6f911d855c3fdbcd5be4e7b82acedad9fd

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\ContainerAwVMSpP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAwVMSpP\App_KernelDevDebugContainer([
    'container.build_hash' => 'AwVMSpP',
    'container.build_id' => 'c76bc80d',
    'container.build_time' => 1710965164,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAwVMSpP');
=======
    \class_alias(\ContainerTx1r1qv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTx1r1qv\App_KernelDevDebugContainer([
    'container.build_hash' => 'Tx1r1qv',
    'container.build_id' => 'aa3f5051',
    'container.build_time' => 1710603164,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTx1r1qv');
>>>>>>> 82883b6f911d855c3fdbcd5be4e7b82acedad9fd
